#!/usr/bin/perl -w
# 这是一个 Perl 脚本，它用于自动生成一部分用户空间程序所需的系统调用接口代码

# Generate usys.S, the stubs for syscalls.
# 在操作系统的上下文中，"the stubs for syscalls" 指的是系统调用的存根（stubs）。
# 这些存根是系统调用接口的一部分，通常位于用户空间和内核空间的边界。
# 它们的主要作用是为系统调用提供一个可被用户空间代码（如应用程序）调用的接口，同时处理必要的转换和准备工作，使得系统调用能够被内核正确处理。
# 简而言之，系统调用存根是用户空间程序与操作系统内核之间通信的桥梁，它们使得用户程序能够以函数调用的形式请求内核提供的服务。
# 这些存根隐藏了用户程序与内核之间的复杂交互细节，简化了用户程序的编写。

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("trace");
entry("sysinfo");